### ISSUE TITLE
Add option to invert colors

### ISSUE THREAD

**Issue by Mhowser** [LachlanArthur/Braille-ASCII-Art#1]
It would be great if there was an option to invert the output of the text on the website. Thanks for making this btw, really handy for yourworldoftext.com!

**Comment by E-Rockalanche** [comment]
Yeah, this tool desperately needs an invert option for dark mode users

**Comment by LachlanArthur** [comment]
Done
https://github.com/LachlanArthur/Braille-ASCII-Art/commit/ba8d77dcadf786351f18383616d1d433eb0804e3

**Comment by Mhowser** [comment]
Thank you so much!
